### ISSUE TITLE
[Refactoring] Implement Test Container Support for JUnit Simplification

### ISSUE THREAD

**Issue by rmhari** [techatpark/gurukulams-notebook#8]
Subject: Implementing Test Container Support for JUnit Simplification

Description:
This initiative aims to enhance our JUnit testing process by introducing Test Container support. Test Containers facilitate the management of external dependencies, such as databases and message queues, streamlining configuration and providing a consistent testing environment.

Key Features:

Containerized Dependencies: Manage external services in Docker containers for consistency.
Configuration Management: Simplify external service setup with version-controlled configurations.
Dynamic Environments: Start and stop containers dynamically during JUnit test execution.
Compatibility: Ensure compatibility with project-relevant external services.
Benefits:

Improved Reliability: Ensure consistent and reproducible test results.
Simplified Setup: Reduce effort in managing external dependencies.
Scalability: Easily adapt to changes in testing requirements.
Implementation Plan:

Research and configure Test Container modules for project dependencies.
Integrate Test Containers into existing JUnit testing framework.
Update documentation for developer guidance.
Testing:

Thoroughly test JUnit integration with Test Containers.
Validate compatibility with project-used databases, message brokers, etc.

Dependencies:

Docker installed on development and testing machines.

Note:
This initiative aligns with our commitment to code quality, robust testing, and improved developer productivity, enhancing overall project stability.

**Comment by SumaNaidu-git** [comment]
we can't do this technically, because after migrating this to TestContainers. Postgres instance is available only at the time of test case execution.
But, we need Postgres instance to generate source code at compiled process. Its impacted to Whole, so we can't do this.

**Comment by sathishk** [comment]
We shall close this ticket
